# Generated by Django 4.1.1 on 2022-09-07 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_news_shop_sizes_news_views_alter_news_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='shop_sizes',
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 7, 19, 46, 4, 694862, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
    ]
