# Generated by Django 4.1.1 on 2022-09-11 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_news_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 11, 12, 32, 47, 238547, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
    ]
